### ISSUE TITLE
Build fails after branch nim1.2 merge

### ISSUE THREAD

**Issue by dkiziridis** [ftsf/nimsynth#9]
nim: 1.2.4
nimble: 0.11.4
make: 4.3
Arch Linux: 5.4.52

Reproduce by running

- nimble -y install sndfile nico
- make

[build_fail.log](https://github.com/ftsf/nimsynth/files/4969583/build_fail.log)

**Comment by ftsf** [comment]
Thanks for the report, will have a fix shortly

**Comment by ftsf** [comment]
Should be fixed now. Let me know if you still have issues.

**Comment by dkiziridis** [comment]
Yep, builds fine now.
